[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "production"

# Health check configuration
[environments.production.healthcheck]
path = "/api/health"
interval = 30
timeout = 10

# Resource configuration
[environments.production.resources]
memory = 512
cpu = 0.5

# Port configuration - Railway will automatically set PORT
[environments.production.networking]
port = "$PORT"